[theme]
background = "#000000"
primary = "#C5C5C5"
secondary = "#C5C5C5"
title = "#D0B3FA"
playing = "#D0B3FA"
playing_selected = "#D0B3FA"
playing_bg = "#181818"
highlight = "#FFFFFF"
highlight_bg = "#323232"
error = "#FFE4E4"
error_bg = "#444444"
statusbar = "#000000"
statusbar_progress = "#D0B3FA"
statusbar_bg = "#D0B3FA"
cmdline = "#FFFFFF"
cmdline_bg = "#444444"
